### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by lddang1762** [lddang1762/lddang1762.github.io#1]
- [ ] Responsive menu
- [ ] Projects Section (when available)
- [ ] Animate sections when scrolled
- [ ] Floating objects in background (asteroids, shooting stars, etc)
- [ ] rocket ship on hero after typewriter
- [x] change favicon
- [x] floating timeline icons
